[build-system]
requires = ["flit_core >=3,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "shifucvefinder"
author = "Yasin Saffari"
author-email = "symbolexe@proton.me"
home-page = "https://github.com/symbolexe/SHIFU"
description-file = "README.md"
license = "MIT"
